name: peritoneal_metastasis
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base=4.3.3
  - conda-forge::r-data.table
  - conda-forge::r-adephylo
  - conda-forge::r-ape
  - conda-forge::r-binom
  - conda-forge::r-biocmanager
  - conda-forge::r-cowplot
  - conda-forge::r-ggplot2
  - conda-forge::r-gmp
  - conda-forge::r-here
  - conda-forge::r-igraph
  - conda-forge::r-phangorn
  - conda-forge::r-phytools
  - conda-forge::r-tidyverse
  - conda-forge::r-data.tree
  - conda-forge::r-caper
  - conda-forge::r-coin
  - conda-forge::r-desctools
  - conda-forge::r-ggpubr
  - conda-forge::r-pheatmap
  - conda-forge::r-reticulate
  - conda-forge::r-treetools
  - conda-forge::r-dendextend
  - conda-forge::r-ggimage
  - conda-forge::r-gplots
  - conda-forge::r-pals
  - conda-forge::r-treedist
  - conda-forge::r-viridis
  - conda-forge::r-devtools
  - bioconda::bioconductor-ggtree
  - bioconda::bioconductor-phyloseq
  - bioconda::bioconductor-biobase
  - bioconda::bioconductor-genomicranges
  - bioconda::bioconductor-qdnaseq
  - bioconda::bioconductor-ace
  - bioconda::bioconductor-mutationalpatterns
  - bioconda::bioconductor-bsgenome.hsapiens.ucsc.hg19
